name: Label New Issues

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Check GitHub context
        run: echo "Issue title: ${{ github.event.issue.title }}"

      - name: Add "To Do" label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            To Do

